### ISSUE TITLE
HTML inside the Layout is not displayed

### ISSUE THREAD

**Issue by jeffrfinn** [smsohan/MvcMailer#120]
Hi I have the following layout

``` html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h1>Mailer</h1>
        <div>
            @RenderBody()
        </div>

        Thanks
    </body>
</html>
```

When I open the email that was generated, it only displays what is rendered by render body. Any other HTML inside the body tag is not in the email. I can't figure out why this is happening

**Comment by DaveNavarro** [comment]
Hello Jeff,

Here's what's in my _Layout.cshtml file;

<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    @RenderBody()
</body>
</html>

As you can see it's just a little different, but perhaps it's enough to correct your issue?

Also, the Body has all the html text I wish to show / share with the recipient.

Hope this helps,

~ Dave

David Navarro
Office Automated Systems
(209) 728-2879 (Office)
(209) 768-2871 (Cell)
.... .- ...- .   .-   -. .. -.-. .   -.. .- -.--

**Comment by jeffrfinn** [comment]
Hi I tried this but still the same result. I wan't to have some HTML in the _Layout so common parts can be used across different emails

**Comment by DaveNavarro** [comment]
Hello,

The message you sent earlier showed your layout as;

---

<!DOCTYPE html>

Mailer

@RenderBody()

```
Thanks
```

</body>

---

Perhaps you're just missing some of the opening / closing elements / tags?
Have you tried adding your text to the sample I sent you?

Like such:

<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
 <body>

  Mailer

  @RenderBody()

  Thanks

 </body>
</html>

I'll give this a try on my server and see what I get.

~ Dave

David Navarro
Office Automated Systems
(209) 728-2879 (Office)
(209) 768-2871 (Cell)
.... .- ...- .   .-   -. .. -.-. .   -.. .- -.--

**Comment by jeffrfinn** [comment]
Thanks that worked, I'm not sure what I was missing but hey it's working now
