### ISSUE TITLE
NuGet Package throws an exception

### ISSUE THREAD

**Issue by pcibraro** [smsohan/MvcMailer#14]
I ran into an issue with the nuget package while trying to add this library to one of my projects. This is the error I got, 

Install-Package : Exception calling "EnumerateFiles" with "3" argument(s): "The path is not of a legal form."

I found the solution after doing some research,

http://drfonz.wordpress.com/2011/03/22/asp-net-mvc-3-mailing-views-successfully-deploying-mvcmailer-in-your-projects/

Thanks
Pablo

**Comment by smsohan** [comment]
This problem is with the nuget installer as it does not remove installed dependent packages when you uninstall a package. So, the residual dependent packages often mess up the things.
