### ISSUE TITLE
Path error from install.ps1

### ISSUE THREAD

**Issue by tathamoddie** [smsohan/MvcMailer#18]
PM> install-package MvcMailer
'T4Scaffolding (≥ 0.9.7)' not installed. Attempting to retrieve dependency from source...
Done.
'EntityFramework (≥ 4.1.10311.0)' not installed. Attempting to retrieve dependency from source...
Done.
You are downloading EntityFramework from Microsoft, the license agreement to which is available at http://go.microsoft.com/fwlink/?LinkID=211010. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'EntityFramework 4.1.10331.0'.
Successfully installed 'T4Scaffolding 0.9.9'.
Successfully installed 'MvcMailer 1.1'.
Successfully added 'EntityFramework 4.1.10331.0' to Web.
Successfully added 'T4Scaffolding 0.9.9' to Web.
Successfully added 'MvcMailer 1.1' to Web.
Exception calling "EnumerateFiles" with "3" argument(s): "The path is not of a legal form."
At C:\Code\MyStory\MyStory\packages\MvcMailer.1.1\tools\install.ps1:8 char:45
-         | %{ [System.IO.Directory]::EnumerateFiles <<<< ($_, "*." + $extension, [System.IO.SearchOption]::AllDirectories) }
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : DotNetMethodException

---------------------------READ ME---------------------------------------------------

Your default Mailer Scaffolder is set to Mailer.Razor

You can generate your Mailers and Views using the following Scaffolder Command

PM> Scaffold Mailer UserMailer Welcome,GoodBye

Edit the smtp configuration at web.config file before you send an email

You can find more at: https://github.com/smsohan/MvcMailer/wiki/MvcMailer-Step-by-Step-Guide

---

**Comment by smsohan** [comment]
Can you please try that on a fresh project? I would assume your project is
located on a local disk instead of a network shared location.

Thank you for trying MvcMailer.

**Comment by tathamoddie** [comment]
Will do - mainly just opened the issue here as a quick place to capture the error for my own investigation later. :)

Project is at C:\Code\Foo\Bar\Baz.sln (different values for Foo, Bar and Baz obviously).
