### ISSUE TITLE
Not getting .Send() and .SendAsync() extension methods?

### ISSUE THREAD

**Issue by southofmarket** [smsohan/MvcMailer#26]
I just installed MvcMailer via Nuget and I do not get the extension methods to send mail. 

When I type this UserMail.Welcome().  I see a bunch of properties like attachments, sender, etc. But no Send or SendAsync

Am I missing something. The Nuget install worked fine with no errors. Using Mvc3 with VS 2010.

Thank you.

**Comment by smsohan** [comment]
using Mvc.Mailer;

## 

Sohan
http://smsohan.com
skype:smsohan | gtalk:sohan39 | cell: 403-714-2673

**Comment by southofmarket** [comment]
Forget it, my bad. Just missing the using Mvc.Mailer
