### ISSUE TITLE
extra . being added to email

### ISSUE THREAD

**Issue by steveoh** [smsohan/MvcMailer#29]
I have a cshtml view thats pretty basic. 

<p>
    Dear @ViewBag.User.Name,</p>
<p>
    We appreciate your interest in the app. Your information has
    been recieved but you have not been granted access. You will receive an email from
    an administrator with further instructions.</p>
<p>
    Your user name is: @ViewBag.User.email</p>
<p>
    Thank you for your patience,</p>

The email sent has two periods on the end of instructions. Thoughts?

It doesn't mess with the period after app either just the one after instructions.

**Comment by smsohan** [comment]
I am not sure I understand your problem. Can you please be more specific?

**Comment by steveoh** [comment]
I have the above view and send an email and it ends up looking like 

Dear User Name,

We appreciate your interest in the app. Your information has been recieved but you have not been granted access. You will receive an email from an administrator with further instructions..

Your user name is: x@y.gov

Thank you for your patience,

**Comment by smsohan** [comment]
What if you add some text right after the dot? Do you still see 2
dots? I think it's coming from your view template.

---

Sent from my iPhone
S M Sohan

On 2011-10-20, at 4:36 PM, steve
reply@reply.github.com
wrote:

**Comment by steveoh** [comment]
If i add text after the period there are still two. i swear i haven't smoked crack today! http://gyazo.com/a54998b7a76f2fd1af99fbe24c6dad0f

**Comment by smsohan** [comment]
Did you try a different email client/address?

---

Sent from my iPhone
S M Sohan

On 2011-10-20, at 4:55 PM, steve
reply@reply.github.com
wrote:

**Comment by steveoh** [comment]
I'm dropping the email on the filesystem. I will try a different email client. Why did you close this issue?

**Comment by steveoh** [comment]
same .. issue in thunderbird

**Comment by smsohan** [comment]
Can you send me a small project with this problem? I can try and
reproduce it locally.

---

Sent from my iPhone
S M Sohan

On 2011-10-24, at 10:48 AM, steve
reply@reply.github.com
wrote:

**Comment by steveoh** [comment]
http://dl.dropbox.com/u/14815756/RoadKill.rar

ding me so i can delete that after you download it.  it's the confirm() that's double perioding.

**Comment by steveoh** [comment]
funky it's not doing it anymore and i didn't change anything.

**Comment by smsohan** [comment]
## Good that I didn't spend time on it :)

Sohan
http://smsohan.com
skype:smsohan | gtalk:sohan39 | cell: 403-714-2673

**Comment by miniragnarok** [comment]
I've had this issue happen in two projects.

When I open the email in Notepad++ there is certainly an extra period. I've managed to recreate it a few times. If for example, you have the number 499.99, it will display as 499..99 if the period is the start of a new line. So in Notepad++ it looks like:

<>Lots of code</> 499=
..99=0D=0A  <>Lots more code</>=

My temporary fix is to add some spaces so that it moves at least one space:

<>Lots of code</> &nb=
sp;499.99=0D=0A  <>Lots more code</>=

**Comment by sjk07** [comment]
This is an Encoding issue that comes from System.Net.Mail
Add this to the SendMail:

Mail.BodyEncoding = System.Text.Encoding.UTF8;
