### ISSUE TITLE
Save HTML to be view in Browser

### ISSUE THREAD

**Issue by khalidabuhakmeh** [smsohan/MvcMailer#38]
I love MvcMailer, but was wondering what the best way to save the rendered email down to a database is. I'd like to essentially cache what was generated so that if a user wants to view the email in a web browser they could do so. Are there any hooks in MvcMailer to do that?

Thanks,

Khalid

**Comment by smsohan** [comment]
You have a mail message object and you should be able to save the
body/subject in a database.

Sent from my iPad

On 2012-01-30, at 7:37 AM, Khalid Abuhakmeh
reply@reply.github.com
wrote:
