### ISSUE TITLE
Nuget Instalation

### ISSUE THREAD

**Issue by southofmarket** [smsohan/MvcMailer#4]
PM> install-package MvcMailer
'T4Scaffolding (≥ 0.9.6)' not installed. Attempting to retrieve dependency from source...
Done
'EFCodeFirst (≥ 0.8)' not installed. Attempting to retrieve dependency from source...
Done
Successfully installed 'EFCodeFirst 0.8'
Successfully installed 'T4Scaffolding 0.9.6'
Successfully installed 'MvcMailer 0.9'
Successfully added 'EFCodeFirst 0.8' to Common
Successfully added 'T4Scaffolding 0.9.6' to Common
Successfully added 'MvcMailer 0.9' to Common

I'm confused by the Nuget installer. What are these installs. I don't see any assemblies other than the mvcmailer.dll. Most importantly is how will this affect deployment? Do I only need the mvcmailer.dll in my bin?

Thank you

**Comment by smsohan** [comment]
The MvcMailer nuget adds only the Mvc.Mailer.dll to your project. 

However, MvcMailer depends on T4 and EF Code first for the scaffolding feature. The dependencies go inside project root > packages folder. These are used from your powershell window as you scaffold mailers. However, in your deployment these are not required and only the Mvc.Mailer.dll will be necessary as you see in your project.
