### ISSUE TITLE
Missing NuGet icon

### ISSUE THREAD

**Issue by frankvaneykelen** [smsohan/MvcMailer#6]
It's a minor thing but it would be nice if MvcMailer had a NuGet icon.

Here's something I made:
https://s3-eu-west-1.amazonaws.com/frankvaneykelen/MvcMailer/MvcMailer.png

Photoshop source:
https://s3-eu-west-1.amazonaws.com/frankvaneykelen/MvcMailer/MvcMailer.psd

I hope you like it, feel free to change it, or request changes!

Cheers,
Frank

**Comment by smsohan** [comment]
Thanks a lot! I have put this icon at NuGet.org, you can see it
http://nuget.org/List/Packages/MvcMailer
