### ISSUE TITLE
Installing MvcMailer corrupts CodedUI tests

### ISSUE THREAD

**Issue by jenshorn** [smsohan/MvcMailer#61]
When MvcMailer is installed via NuGet it is no longer possible to edit UIMaps for CodedUI testing which means it's no longer possible to generate code for new tests. I see the same issue on another computer that has retrieved the code from the source control. When trying to open UIMap or create a new test with Test builder this message pops up:

```
The following package failed to load:
C:\Users\[username]\AppData\Local\assembly\dl3\13YH5408.B6N\D995C8N6.CK1\02143ec0\004bcc37_c67fcd01\Microsoft.VisualStudio.TestTools.UITest.Extension.IE.dll.
```

It is always the same path even on different projects even though it looks like a random cache path. I have deleted the folders manually but they are recreated. Have not been able to check the path on other computers though. So far I have not encountered this issue when installing anything else, that is why I suspect MvcMailer to be the cause. Perhaps it has something to do with T4Scaffolding? However installing that seperately does not cause this behaviour.

Steps to reproduce:
1. Create a new MVC 3 project (Internet, aspx)
2. Add a new project -> Test -> Test project
3. Add Coded UI test to test project
4. Generate some UI test with Coded UI test builder
5. Now it should be possible to open the UIMap.uitest with Coded UI test Editor
6. Install-Package MvcMailer
7. Close down the entire solution (not sure this is required)
8. Open the UIMap.uitest with Coded UI test Editor and you should get the error stated above.

If MvcMailer is uninstalled then it is possible to open the UIMap again (restart of VS might be required). 

A workaround to enable editing uf UIMap again is to unload the MVC project and restart VS, then it is possible to generate code for tests again.

System:
Win7 x64 EN, VS2010 SP1 Ultimate, ASP.NET MVC 3 Tools Update

**Comment by jenshorn** [comment]
Forgot to add that the assembly creating the error (Microsoft.VisualStudio.TestTools.UITest.Extension.IE.dll) is not referenced from any projects in the solution.

**Comment by smsohan** [comment]
Thanks for reporting this. Can you send me some stack trace?

---

Sent from my iPhone
Sohan SM

On 2012-09-27, at 6:51 AM, phrusher notifications@github.com wrote:

When MvcMailer is installed via NuGet it is no longer possible to edit
UIMaps for CodedUI testing which means it's no longer possible to generate
code for new tests. I see the same issue on another computer that has
retrieved the code from the source control. When trying to open UIMap or
create a new test with Test builder this message pops up:

The following package failed to load:
C:\Users[username]\AppData\Local\assembly\dl3\13YH5408.B6N\D995C8N6.CK1\02143ec0\004bcc37_c67fcd01\Microsoft.VisualStudio.TestTools.UITest.Extension.IE.dll.

It is always the same path even on different projects even though it looks
like a random cache path. I have deleted the folders manually but they are
recreated. Have not been able to check the path on other computers though.
So far I have not encountered this issue when installing anything else,
that is why I suspect MvcMailer to be the cause. Perhaps it has something
to do with T4Scaffolding? However installing that seperately does not cause
this behaviour.

Steps to reproduce:
1. Create a new MVC 3 project (Internet, aspx)
2. Add a new project -> Test -> Test project
3. Add Coded UI test to test project
4. Generate some UI test with Coded UI test builder
5. Now it should be possible to open the UIMap.uitest with Coded UI test
   Editor
6. Install-Package MvcMailer
7. Close down the entire solution (not sure this is required)
8. Open the UIMap.uitest with Coded UI test Editor and you should get
   the error stated above.

If MvcMailer is uninstalled then it is possible to open the UIMap again
(restart of VS might be required).

A workaround to enable editing uf UIMap again is to unload the MVC project
and restart VS, then it is possible to generate code for tests again.

System:
Win7 x64 EN, VS2010 SP1 Ultimate, ASP.NET MVC 3 Tools Update

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/61.

**Comment by smsohan** [comment]
MvcMailer uses NUnit for the tests and doesn't refer to Microsoft test
framework.

---

Sent from my iPhone
Sohan SM

On 2012-09-27, at 6:54 AM, phrusher notifications@github.com wrote:

Forgot to add that the assembly creating the error
(Microsoft.VisualStudio.TestTools.UITest.Extension.IE.dll) is not
referenced from any projects in the solution.

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/61#issuecomment-8935008.

**Comment by jenshorn** [comment]
Unfortunately there is no stack trace (that I can find), just the error message in the popup when opening/double clicking UIMap.uitest.

**Comment by jenshorn** [comment]
> MvcMailer uses NUnit for the tests and doesn't refer to Microsoft test framework.

That almost makes it more interesting why that file is displayed in the error.

**Comment by jenshorn** [comment]
Why is this closed? The issue is still present in MvcMailer 4.0.
