### ISSUE TITLE
NuGet package MvcMailer3 Not Complete

### ISSUE THREAD

**Issue by gdessler** [smsohan/MvcMailer#64]
Created a default MvcApplication project template and added the MvCMailer NuGet package.

The Mailer classes have a compiler error:

Error   8   The type or namespace name 'MvcMailMessage' could not be found (are you missing a using directive or an assembly reference?)

There is reference to the MvcMailer.dll classes in the project.  The NuGet package is not installing the compiled assemblies.

**Comment by smsohan** [comment]
Please check the updated version. The older one had a corrupted dll file. Sorry for that.

**Comment by gdessler** [comment]
Great, not a problem.   Nice tool!

**Comment by tim-butler-guardian** [comment]
hmm i just installed from Manage NuGetPackage in VS and got this error, so it might be pulling the old one still fyi

**Comment by caglardursun** [comment]
When I try 2 install from visual studio ui (Not the nuget command line) I got the same error
