### ISSUE TITLE
Updated Nuget package breaks the project

### ISSUE THREAD

**Issue by justSteve** [smsohan/MvcMailer#65]
Just stepped into Nuget to see what components offered updates. Installed MvcMailer.4.0.nupkg without error but now the project will not compile:

Error   34  Assembly 'Mvc.Mailer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'   g:\Code\TTS\packages\MvcMailer.4.0\lib\40\Mvc.Mailer.dll    TTS

**Comment by smsohan** [comment]
Please try MvcMailer3 for asp.net mvc 3 projects.

---

Sent from my iPhone
Sohan SM

On 2012-10-11, at 11:03 AM, justSteve notifications@github.com wrote:

Just stepped into Nuget to see what components offered updates. Installed
MvcMailer.4.0.nupkg without error but now the project will not compile:

Error 34 Assembly 'Mvc.Mailer, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher
version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35'
g:\Code\TTS\packages\MvcMailer.4.0\lib\40\Mvc.Mailer.dll TTS

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/65.

**Comment by justSteve** [comment]
I've tried that - uninstalled the update; then installed mvc3. Nuget installed it without error but no MVC.Mailer3 is in References - and no compile - the type or namespace 'Mvc' could not be found....

is the code downloadable to let me compile a dll on my own?

isn't nuget supposed to be smarter than this?

**Comment by justSteve** [comment]
Never mind re SC - I found one in a backup folder and can compile my project again - whew.

**Comment by mbirkes** [comment]
I have an MVC3 project, but MvcMail3 also does not compile with the project.

Assembly 'Mvc.Mailer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'   

I tried both MvcMailer and MvcMailer3 (uninstalling and installing each) and the same error occurs. However I can see that the MvcMailer assembly is different for each install (different size) but still requires MVC4.

**Comment by smsohan** [comment]
Hi there:
For Mvc3 project please use MvcMailer 3 only. Let me share a sample Mvc3 project in a bit.

**Comment by smsohan** [comment]
Please look at https://github.com/smsohan/MvcMailer3-Example for a working example of MvcMailer 3 on a Mvc3 project. I started with a blank Mvc3 project and added a nuget reference to MvcMailer 3.
