### ISSUE TITLE
New error while using the non-updated .dll

### ISSUE THREAD

**Issue by justSteve** [smsohan/MvcMailer#66]
Though the project will now compile, attempting to view any page in my site tosses the same error as described here.

http://stackoverflow.com/questions/5228590/required-attribute-pagebasetype-not-found-ysod-when-launching-my-mvc-3-appli

**Comment by smsohan** [comment]
He Steve:
I have pushed an update. The older one somehow got the dll file corrupted. Please check if it works with the new version.
