### ISSUE TITLE
MvcMailer 4.0 does not contain a definition for 'Send' and no extension method 'Send'

### ISSUE THREAD

**Issue by leniel** [smsohan/MvcMailer#68]
Hi,

In my ASP.NET MVC 4 app I just updated the NuGet package to v. 4.0 and now I get this error message:

```
Error 'System.Net.Mail.MailMessage' does not contain a definition for 'Send' and no extension method 'Send' accepting a first argument of type 'System.Net.Mail.MailMessage' could be found (are you missing a using directive or an assembly reference?)
```

I do have a `using Mvc.Mailer;` in my controller.

Is something missing in the new NuGet package? I ask this because you made an overall update according to #62.

**Comment by smsohan** [comment]
## Please use the MvcMailMessage object instead.

Sohan
http://smsohan.com
skype:smsohan | gtalk:sohan39 | cell: 403-714-2673

**Comment by leniel** [comment]
Oh... nice Sohan. Works great now!

I was almost regenerating my mailers to see if they would be created differently.

Now I see that the `MailerBase.Populate` method returns a `MvcMailMessage` instead of `MailMessage`.

Thanks for the awesome library.

All the best,

Leniel

**Comment by smsohan** [comment]
Thanks Leniel, good to know its working.

## 

Sohan
http://smsohan.com
skype:smsohan | gtalk:sohan39 | cell: 403-714-2673
