### ISSUE TITLE
Build error in Mvc 3 and 4: "Mvc Mailer v1 uses Mvc v4 which has higher version than referenced assembly 'Mvc v3'"    

### ISSUE THREAD

**Issue by mos-ie** [smsohan/MvcMailer#70]
I'v tried to install MvcMailer via package manager in an Mvc 3 and Mvc 4 project, but every time I get the following error and warning:

Error   1   Assembly 'Mvc.Mailer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'   c:\Users\Home\Desktop\MVCMailerTestApp\packages\MvcMailer.4.0\lib\40\Mvc.Mailer.dll MVCMailerTestApp

Warning 2   Found conflicts between different versions of the same dependent assembly.  MVCMailerTestApp

I'm using VS2010. Any ideas as to what could be causing the above? Help appreciated.

**Comment by smsohan** [comment]
Please use MvcMailer3 package for aspnet mvc 3 project.

---

Sent from my iPhone
Sohan SM

On 2012-11-12, at 7:51 AM, matthewosullivan87 notifications@github.com
wrote:

I'v tried to install MvcMailer via package manager in an Mvc 3 and Mvc 4
project, but every time I get the following error and warning:

Error 1 Assembly 'Mvc.Mailer, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null' uses 'System.Web.Mvc, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher
version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35'
c:\Users\Home\Desktop\MVCMailerTestApp\packages\MvcMailer.4.0\lib\40\Mvc.Mailer.dll
MVCMailerTestApp

Warning 2 Found conflicts between different versions of the same dependent
assembly. MVCMailerTestApp

I'm using VS2010. Any ideas as to what could be causing the above? Help
appreciated.

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/70.

**Comment by mos-ie** [comment]
Thanks that resolved the issue.
