### ISSUE TITLE
msg.Send() method

### ISSUE THREAD

**Issue by sp4ceman** [smsohan/MvcMailer#8]
I was wondering if it wouldn't be better moving the Send() extension method out of the Mvc.Mailer namespace into the Web.Mailers namespace.

That way your code behind files only need one using statement. 
Its a small change, but it took me ages to find the namespace for the send method.

Like I said, just a suggestion.
Thanks for an awesome project

**Comment by smsohan** [comment]
In the wiki, I put an explicit mention of this fact. However, I am editing the wiki to make it even more clear. Btw, did you see the wiki or some other article where it mentions the Send method?
