### ISSUE TITLE
There needs to be some mention of the license for MvcMailer somewhere in the wiki

### ISSUE THREAD

**Issue by lee-elenbaas** [smsohan/MvcMailer#86]
There needs to be some mention of the license for MvcMailer somewhere in the wiki
And while we are at it - what is the license for MvcMailer

**Comment by smsohan** [comment]
You can find the licence linked at http://nuget.org/packages/MvcMailer

Sent from my iPad

On 2013-02-17, at 11:52 PM, Lee Elenbaas notifications@github.com wrote:

There needs to be some mention of the license for MvcMailer somewhere in
the wiki
And while we are at it - what is the license for MvcMailer

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/86.
