### ISSUE TITLE
Is there anyway to send a message part with text/calendar content type?

### ISSUE THREAD

**Issue by escobar5** [smsohan/MvcMailer#89]
Hi, I'm trying to send a multipart email and one of the parts is an ICS. I saw that mvcmailer can send multipart emails with both text/plain and text/html parts, but can I send one with a text/calendar content type from mvcmailer?

**Comment by smsohan** [comment]
As of now, you can add that part yourself to the mail message object. I'll
see it can be done in a future version.

---

Sent from my iPhone
Sohan SM

On 2013-03-07, at 3:34 PM, "Juan S. Escobar" notifications@github.com
wrote:

Hi, I'm trying to send a multipart email and one of the parts is an ICS. I
saw that mvcmailer can send multipart emails with both text/plain and
text/html parts, but can I send one with a text/calendar content type from
mvcmailer?

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/89
.

**Comment by escobar5** [comment]
Ok, thanks
