### ISSUE TITLE
Why the reference to EF?

### ISSUE THREAD

**Issue by adambient** [smsohan/MvcMailer#9]
First of all I just want to say thanks for creating this great little framework, I've previously used MonoRail which comes with something similar and I've always thought this was missing from MVC.

I just wondered why the nuget has a dependancy on Entity Framework? It's not really a problem but I'm not using EF in the rest of my application and the OCD part of me would prefer there not to be a reference.

Cheers,

Adam.

**Comment by smsohan** [comment]
Hi Adam:
Thank you for contacting. MvcMailer uses T4Scaffolding to generate the
mailers and their view templates. This T4Scaffolding is from Microsoft and I
hope they will remove the dependency on EF. However, your project doesn't
need to get a reference to EF and I guess installing MvcMailer won't add
that reference to your project. Its just needed for scaffolding.

## Cheers!

Sohan
http://smsohan.com
skype:smsohan | gtalk:sohan39 | cell: 403-714-2673
