### ISSUE TITLE
Scaffold Error ?

### ISSUE THREAD

**Issue by pantsclunk** [smsohan/MvcMailer#90]
I'm using VS 2012 with an MVC 4 project. I installed mvcMailer via nuget. It installs fine, then I go to scaffold and get this? Makes no sense? Please help.

thanks

PM> scaffold mailer.razor welcome
cmdlet Invoke-Scaffolder at command pipeline position 1
Supply values for the following parameters:
MailerMethods[0]:

**Comment by smsohan** [comment]
The error message says it. The command expects the name of the mailer
followed by its methods. Scaffold Mailer Welcome NewUser,Activation

---

Sent from my iPhone
Sohan SM

On 2013-03-18, at 8:55 PM, sfuptown notifications@github.com wrote:

I'm using VS 2012 with an MVC 4 project. I installed mvcMailer via nuget.
It installs fine, then I go to scaffold and get this? Makes no sense?
Please help.

thanks

PM> scaffold mailer.razor welcome
cmdlet Invoke-Scaffolder at command pipeline position 1
Supply values for the following parameters:
MailerMethods[0]:

—
Reply to this email directly or view it on
GitHubhttps://github.com/smsohan/MvcMailer/issues/90
.

**Comment by pantsclunk** [comment]
Thank you for the quick response. It just worked for me. 

Thanks
