### ISSUE TITLE
How do you add multiple addresses to the MailAddressCollection CC

### ISSUE THREAD

**Issue by doug-coates** [smsohan/MvcMailer#97]
We are using distribution list for groups but is there a way to add multiple addresses to the MailAddressCollection CC
I'm using the following function to load the MVCMailerMessage. Can you provide a example how to load a list of addresses into the MailAddressCollection CC

  public virtual MvcMailMessage InternalReview(Email e)
  {
            ViewData.Model = e;

```
        return Populate(x =>
        {
            x.Subject = "List Added";
            x.ViewName = "InternalReview";
            x.To.Add(e.to);
            x.CC.Add(e.co);
        });
```

   } 

Thanks Doug

**Comment by smsohan** [comment]
You can keep adding more addresses by `x.To.Add` or `x.CC.Add`

**Comment by doug-coates** [comment]
I’m passing in a email class that has string[] of recipients…
Is there a way of adding a foreach loop from an array of strings

foreach (string address in recipient)
{
    x.CC.Add(address);
}

Douglas Coates
Application Architect
t: 616.393.1509 | c: 616.666.6842 | f: 616.393.3584 | e: doug.coates@haworth.com
One Haworth Center, Holland, MI 49423-9576 USA | 616.393.3000
haworth.com

[cid:image001.png@01CE524D.35C7F7A0]

Notice of Confidentiality: This message and any attachments are confidential.  If you are not the intended recipient, please do not read or distribute it.  Alert the sender by reply email and delete this message immediately.

**Comment by smsohan** [comment]
You can do something like this:

```
recipients.ForEach(recipient => x.CC.Add(recipient))
```
